---
title: "Statistics 101: Bayesian Edition"
author: "Ben Buzzee"
permalink: /posts/2018/06/blog-post-2/
date: "June 26, 2018"
output: html_document
---

This post is an attempt to piece together a coherent picture of how statistics should be used.



 * "Claims that confidence intervals yield an
index of precision, that the values within them are plausible,
and that the confidence coefficient can be read as
a measure of certainty that the interval contains the true
value, are all fallacies and unjustified by confidence interval
theory." - The fallacy of placing confidence in confidence intervals

 * "The reason students have problems understanding hypothesis
tests is that they may be trying to think." - The Insignificance of Statistical Significance Testing

 * "Example number one: the confidence interval. Its definition is so con-
trived and anti-intuitive that it's no wonder that students have difficulties
ingesting it." - William Briggs

 * "It is unanimously agreed that statistics depends somehow on probability. But, as to what probability is and how it is connected with statistics, there has seldom been such complete disagreement and breakdown of communication since the Tower of Babel. Doubtless, much of the disagreement is merely terminological and would disappear under sufficiently sharp analysis." Savage, 1954, pg 9


Logical Foundations: How does statistical evidence lead to understanding "truth" in nature? Popperian style falsification? Are hypothesis tests useful or are they misleading? "Accepting the Alternative?" A statistical procedure needs to be paired with a logical framework in order to draw conclusions about the natural world.

Statistical Evidence: P-values, effect size, likelihood ratios, posterior probabilities




